#!/usr/bin/env bash
# Razen Language Help Script
# Copyright © 2025 Prathmesh Barot, Basai Corporation
# Version: beta v0.1.2

# ANSI colors
BLUE="\033[0;34m"
GREEN="\033[0;32m"
RED="\033[0;31m"
YELLOW="\033[0;33m"
PURPLE="\033[0;35m"
CYAN="\033[0;36m"
NC="\033[0m" # No Color

# Print banner
echo -e "${BLUE}"
echo "██████╗  █████╗ ███████╗███████╗███╗   ██╗"
echo "██╔══██╗██╔══██╗╚══███╔╝██╔════╝████╗  ██║"
echo "██████╔╝███████║  ███╔╝ █████╗  ██╔██╗ ██║"
echo "██╔══██╗██╔══██║ ███╔╝  ██╔══╝  ██║╚██╗██║"
echo "██║  ██║██║  ██║███████╗███████╗██║ ╚████║"
echo "╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═══╝"
echo -e "${NC}"
echo -e "${YELLOW}Programming Language ${PURPLE}beta v0.1.2${NC}"
echo -e "${CYAN}By Prathmesh Barot, Basai Corporation${NC}"
echo -e "${YELLOW}Copyright © 2025 Prathmesh Barot${NC}\n"

# Print usage information
echo -e "${BLUE}USAGE${NC}"
echo -e "  ${GREEN}razen${NC} [command] [options] [file]"
echo -e "  ${GREEN}razen-debug${NC} [options] [file]"
echo -e "  ${GREEN}razen-test${NC} [options] [file]"
echo -e "  ${GREEN}razen-run${NC} [options] [file]"
echo -e "  ${GREEN}razen-update${NC} [options]"
echo -e "  ${GREEN}razen-help${NC} [command]"
echo -e "  ${GREEN}razen new${NC} [program_name]"
echo -e "  ${GREEN}razen uninstall${NC} - Remove Razen from your system\n"

# Print command details
echo -e "${BLUE}COMMAND DETAILS${NC}"
echo -e "  ${GREEN}razen${NC} - Run a Razen program"
echo -e "  ${GREEN}razen-debug${NC} - Run a program in debug mode"
echo -e "  ${GREEN}razen-test${NC} - Run a program in test mode"
echo -e "  ${GREEN}razen-run${NC} - Run a program with clean output"
echo -e "  ${GREEN}razen-update${NC} - Update Razen to the latest version"
echo -e "  ${GREEN}razen-help${NC} - Display this help message"
echo -e "  ${GREEN}razen new${NC} - Create a new Razen program"
echo -e "  ${GREEN}razen uninstall${NC} - Remove Razen from your system\n"

# Print examples
echo -e "${BLUE}EXAMPLES${NC}"
echo -e "  ${GREEN}razen run hello_world.rzn${NC} - Run a Razen program"
echo -e "  ${GREEN}razen-debug program.rzn${NC} - Run a program in debug mode"
echo -e "  ${GREEN}razen-test program.rzn${NC} - Run a program in test mode"
echo -e "  ${GREEN}razen-run program.rzn${NC} - Run a program with clean output"
echo -e "  ${GREEN}razen-update${NC} - Update Razen to the latest version"
echo -e "  ${GREEN}razen new myprogram${NC} - Create a new program"
echo -e "  ${GREEN}razen uninstall${NC} - Remove Razen from your system\n"

echo -e "${GREEN}FILES LOCATION:${NC}"
echo -e "  Core files:    /usr/local/lib/razen"
echo -e "  Examples:      /usr/local/lib/razen/examples"
echo -e "  Scripts:       /usr/local/lib/razen/scripts"
echo ""
echo -e "${RED}UNINSTALL:${NC}"
echo -e "  razen-uninstall" 